window.workbenchData = {
  "summary": {
    "earnedPremium": 738131771,
    "writtenPremium": 760496647,
    "lossRatio": 79.9,
    "combinedRatio": 102.7,
    "retention": 78.9,
    "segments": 96,
    "states": 6,
    "filingItems": 24,
    "requirements": 8
  },
  "states": {
    "WA": {
      "earnedPremium": 122089490,
      "lossRatio": 77.1,
      "combinedRatio": 100.0,
      "retention": 79.7,
      "actionCount": 7
    },
    "OR": {
      "earnedPremium": 114862204,
      "lossRatio": 74.3,
      "combinedRatio": 97.8,
      "retention": 79.9,
      "actionCount": 6
    },
    "ID": {
      "earnedPremium": 113768027,
      "lossRatio": 72.7,
      "combinedRatio": 96.2,
      "retention": 81.2,
      "actionCount": 5
    },
    "CO": {
      "earnedPremium": 131648171,
      "lossRatio": 83.8,
      "combinedRatio": 106.6,
      "retention": 77.7,
      "actionCount": 10
    },
    "CA": {
      "earnedPremium": 136564319,
      "lossRatio": 90.4,
      "combinedRatio": 113.3,
      "retention": 76.0,
      "actionCount": 11
    },
    "WY": {
      "earnedPremium": 119199560,
      "lossRatio": 79.0,
      "combinedRatio": 102.2,
      "retention": 78.9,
      "actionCount": 7
    }
  },
  "actionQueue": [
    {
      "segment_id": "CO-AU-03",
      "state": "CO",
      "state_name": "Colorado",
      "product_line": "Auto",
      "territory": "Wildland interface",
      "geography_type": "wildfire",
      "rate_environment": "complex",
      "exposure_index": 61.3,
      "inspection_completion": 67.9,
      "telematics_eligible": 50.1,
      "automation_approval_rate": 47.0,
      "guideline_exception_rate": 37.4,
      "baseline_retention": 70.5,
      "owner": "Product",
      "earned_premium": 10327556,
      "written_premium": 10531555,
      "incurred_losses": 10150070,
      "loss_ratio": 98.3,
      "combined_ratio": 123.6,
      "retention": 70.1,
      "claim_frequency": 10.3,
      "target_gap": 29.6,
      "rate_indication": 18,
      "review_score": 73.4,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "CO-FR-03",
      "state": "CO",
      "state_name": "Colorado",
      "product_line": "Farm and Ranch",
      "territory": "Wildland interface",
      "geography_type": "wildfire",
      "rate_environment": "complex",
      "exposure_index": 61.3,
      "inspection_completion": 67.3,
      "telematics_eligible": 31.3,
      "automation_approval_rate": 46.3,
      "guideline_exception_rate": 36.2,
      "baseline_retention": 75.4,
      "owner": "Underwriting",
      "earned_premium": 7244669,
      "written_premium": 7436384,
      "incurred_losses": 7496522,
      "loss_ratio": 103.5,
      "combined_ratio": 132.5,
      "retention": 74.6,
      "claim_frequency": 10.6,
      "target_gap": 38.5,
      "rate_indication": 18,
      "review_score": 83.5,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "CO-FR-04",
      "state": "CO",
      "state_name": "Colorado",
      "product_line": "Farm and Ranch",
      "territory": "Mountain and hail belt",
      "geography_type": "weather",
      "rate_environment": "complex",
      "exposure_index": 54.2,
      "inspection_completion": 69.0,
      "telematics_eligible": 37.2,
      "automation_approval_rate": 48.3,
      "guideline_exception_rate": 28.2,
      "baseline_retention": 77.4,
      "owner": "Actuarial",
      "earned_premium": 7562563,
      "written_premium": 7845273,
      "incurred_losses": 7376158,
      "loss_ratio": 97.5,
      "combined_ratio": 126.8,
      "retention": 76.5,
      "claim_frequency": 9.7,
      "target_gap": 32.8,
      "rate_indication": 18,
      "review_score": 70.7,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "CA-HO-03",
      "state": "CA",
      "state_name": "California",
      "product_line": "Home",
      "territory": "Wildland interface",
      "geography_type": "wildfire",
      "rate_environment": "complex",
      "exposure_index": 71.2,
      "inspection_completion": 70.5,
      "telematics_eligible": 33.6,
      "automation_approval_rate": 39.3,
      "guideline_exception_rate": 39.4,
      "baseline_retention": 71.9,
      "owner": "Product",
      "earned_premium": 13928513,
      "written_premium": 14317271,
      "incurred_losses": 13521559,
      "loss_ratio": 97.1,
      "combined_ratio": 126.3,
      "retention": 71.3,
      "claim_frequency": 10.1,
      "target_gap": 32.3,
      "rate_indication": 18,
      "review_score": 80.1,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "CA-HO-04",
      "state": "CA",
      "state_name": "California",
      "product_line": "Home",
      "territory": "Mountain and hail belt",
      "geography_type": "weather",
      "rate_environment": "complex",
      "exposure_index": 63.7,
      "inspection_completion": 71.4,
      "telematics_eligible": 29.3,
      "automation_approval_rate": 41.8,
      "guideline_exception_rate": 36.2,
      "baseline_retention": 71.8,
      "owner": "Underwriting",
      "earned_premium": 13863420,
      "written_premium": 14277518,
      "incurred_losses": 13021507,
      "loss_ratio": 93.9,
      "combined_ratio": 123.8,
      "retention": 71.3,
      "claim_frequency": 9.9,
      "target_gap": 29.8,
      "rate_indication": 18,
      "review_score": 73.2,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "CA-AU-03",
      "state": "CA",
      "state_name": "California",
      "product_line": "Auto",
      "territory": "Wildland interface",
      "geography_type": "wildfire",
      "rate_environment": "complex",
      "exposure_index": 71.2,
      "inspection_completion": 63.6,
      "telematics_eligible": 49.5,
      "automation_approval_rate": 35.9,
      "guideline_exception_rate": 36.2,
      "baseline_retention": 70.0,
      "owner": "Underwriting",
      "earned_premium": 10425072,
      "written_premium": 10762363,
      "incurred_losses": 10812389,
      "loss_ratio": 103.7,
      "combined_ratio": 129.2,
      "retention": 70.1,
      "claim_frequency": 10.4,
      "target_gap": 35.2,
      "rate_indication": 18,
      "review_score": 85.2,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "CA-AU-04",
      "state": "CA",
      "state_name": "California",
      "product_line": "Auto",
      "territory": "Mountain and hail belt",
      "geography_type": "weather",
      "rate_environment": "complex",
      "exposure_index": 63.7,
      "inspection_completion": 74.5,
      "telematics_eligible": 47.5,
      "automation_approval_rate": 43.8,
      "guideline_exception_rate": 34.9,
      "baseline_retention": 71.2,
      "owner": "Actuarial",
      "earned_premium": 11126847,
      "written_premium": 11523766,
      "incurred_losses": 10813432,
      "loss_ratio": 97.2,
      "combined_ratio": 123.8,
      "retention": 70.1,
      "claim_frequency": 9.8,
      "target_gap": 29.8,
      "rate_indication": 18,
      "review_score": 71.2,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "CA-FR-03",
      "state": "CA",
      "state_name": "California",
      "product_line": "Farm and Ranch",
      "territory": "Wildland interface",
      "geography_type": "wildfire",
      "rate_environment": "complex",
      "exposure_index": 71.2,
      "inspection_completion": 69.7,
      "telematics_eligible": 29.4,
      "automation_approval_rate": 36.1,
      "guideline_exception_rate": 37.0,
      "baseline_retention": 73.6,
      "owner": "Actuarial",
      "earned_premium": 7790702,
      "written_premium": 8193163,
      "incurred_losses": 8864640,
      "loss_ratio": 113.8,
      "combined_ratio": 142.5,
      "retention": 72.9,
      "claim_frequency": 10.3,
      "target_gap": 48.5,
      "rate_indication": 18,
      "review_score": 98.4,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "CA-FR-04",
      "state": "CA",
      "state_name": "California",
      "product_line": "Farm and Ranch",
      "territory": "Mountain and hail belt",
      "geography_type": "weather",
      "rate_environment": "complex",
      "exposure_index": 63.7,
      "inspection_completion": 68.4,
      "telematics_eligible": 37.1,
      "automation_approval_rate": 44.1,
      "guideline_exception_rate": 35.3,
      "baseline_retention": 76.8,
      "owner": "Claims",
      "earned_premium": 6765726,
      "written_premium": 7058660,
      "incurred_losses": 6993675,
      "loss_ratio": 103.4,
      "combined_ratio": 131.3,
      "retention": 76.7,
      "claim_frequency": 10.5,
      "target_gap": 37.3,
      "rate_indication": 18,
      "review_score": 82.2,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "WY-AU-03",
      "state": "WY",
      "state_name": "Wyoming",
      "product_line": "Auto",
      "territory": "Wildland interface",
      "geography_type": "wildfire",
      "rate_environment": "light",
      "exposure_index": 51.4,
      "inspection_completion": 70.6,
      "telematics_eligible": 46.6,
      "automation_approval_rate": 47.1,
      "guideline_exception_rate": 26.5,
      "baseline_retention": 72.2,
      "owner": "Actuarial",
      "earned_premium": 9226044,
      "written_premium": 9523006,
      "incurred_losses": 8613718,
      "loss_ratio": 93.4,
      "combined_ratio": 119.0,
      "retention": 71.2,
      "claim_frequency": 8.9,
      "target_gap": 25.0,
      "rate_indication": 18,
      "review_score": 59.8,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "WY-FR-03",
      "state": "WY",
      "state_name": "Wyoming",
      "product_line": "Farm and Ranch",
      "territory": "Wildland interface",
      "geography_type": "wildfire",
      "rate_environment": "light",
      "exposure_index": 51.4,
      "inspection_completion": 67.2,
      "telematics_eligible": 35.7,
      "automation_approval_rate": 47.7,
      "guideline_exception_rate": 30.6,
      "baseline_retention": 76.7,
      "owner": "Claims",
      "earned_premium": 6616953,
      "written_premium": 6783193,
      "incurred_losses": 6482481,
      "loss_ratio": 98.0,
      "combined_ratio": 126.7,
      "retention": 77.5,
      "claim_frequency": 10.2,
      "target_gap": 32.7,
      "rate_indication": 18,
      "review_score": 71.6,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "CO-AU-04",
      "state": "CO",
      "state_name": "Colorado",
      "product_line": "Auto",
      "territory": "Mountain and hail belt",
      "geography_type": "weather",
      "rate_environment": "complex",
      "exposure_index": 54.2,
      "inspection_completion": 68.9,
      "telematics_eligible": 48.0,
      "automation_approval_rate": 45.0,
      "guideline_exception_rate": 32.0,
      "baseline_retention": 71.9,
      "owner": "Underwriting",
      "earned_premium": 10484013,
      "written_premium": 11029824,
      "incurred_losses": 9655384,
      "loss_ratio": 92.1,
      "combined_ratio": 117.8,
      "retention": 71.0,
      "claim_frequency": 9.4,
      "target_gap": 23.8,
      "rate_indication": 18,
      "review_score": 62.4,
      "action_score": 99.1,
      "recommendation": "Tighten guideline and inspection trigger"
    }
  ],
  "filingQueue": [
    {
      "state": "CO",
      "product_line": "Farm and Ranch",
      "earned_premium": 28546028,
      "loss_ratio": 92.4,
      "combined_ratio": 121.4,
      "rate_indication": 16,
      "proposed_rate_change": 12,
      "filing_complexity": "High",
      "readiness_score": 35,
      "filing_status": "Needs product owner decision",
      "manual_sections": "Eligibility; Deductible options; Inspection trigger",
      "form_or_rule_dependency": "Eligibility",
      "owner": "IT"
    },
    {
      "state": "CA",
      "product_line": "Farm and Ranch",
      "earned_premium": 29886314,
      "loss_ratio": 100.0,
      "combined_ratio": 128.8,
      "rate_indication": 16,
      "proposed_rate_change": 12,
      "filing_complexity": "High",
      "readiness_score": 35,
      "filing_status": "Needs product owner decision",
      "manual_sections": "Telematics discount; Renewal review; Deductible options",
      "form_or_rule_dependency": "Telematics discount",
      "owner": "Actuarial"
    },
    {
      "state": "CA",
      "product_line": "Auto",
      "earned_premium": 42752624,
      "loss_ratio": 92.1,
      "combined_ratio": 117.6,
      "rate_indication": 15.9,
      "proposed_rate_change": 11.9,
      "filing_complexity": "High",
      "readiness_score": 38.5,
      "filing_status": "Needs product owner decision",
      "manual_sections": "Farm outbuilding coverage; Eligibility; Protection class",
      "form_or_rule_dependency": "Farm outbuilding coverage",
      "owner": "Underwriting"
    },
    {
      "state": "WY",
      "product_line": "Farm and Ranch",
      "earned_premium": 27350121,
      "loss_ratio": 87.3,
      "combined_ratio": 116.2,
      "rate_indication": 15.0,
      "proposed_rate_change": 11.2,
      "filing_complexity": "High",
      "readiness_score": 40.3,
      "filing_status": "Needs product owner decision",
      "manual_sections": "Renewal review; Protection class; Inspection trigger",
      "form_or_rule_dependency": "Renewal review",
      "owner": "Product"
    },
    {
      "state": "CA",
      "product_line": "Home",
      "earned_premium": 53518256,
      "loss_ratio": 87.8,
      "combined_ratio": 117.2,
      "rate_indication": 15.6,
      "proposed_rate_change": 11.7,
      "filing_complexity": "High",
      "readiness_score": 41.8,
      "filing_status": "Needs product owner decision",
      "manual_sections": "Eligibility; Farm outbuilding coverage; Deductible options",
      "form_or_rule_dependency": "Eligibility",
      "owner": "Product"
    },
    {
      "state": "CO",
      "product_line": "Auto",
      "earned_premium": 40417997,
      "loss_ratio": 87.6,
      "combined_ratio": 112.9,
      "rate_indication": 13.0,
      "proposed_rate_change": 9.7,
      "filing_complexity": "High",
      "readiness_score": 44.6,
      "filing_status": "Needs product owner decision",
      "manual_sections": "Inspection trigger; Eligibility; Farm outbuilding coverage",
      "form_or_rule_dependency": "Inspection trigger",
      "owner": "Claims"
    },
    {
      "state": "WA",
      "product_line": "Farm and Ranch",
      "earned_premium": 27316507,
      "loss_ratio": 85.0,
      "combined_ratio": 113.7,
      "rate_indication": 13.4,
      "proposed_rate_change": 10.1,
      "filing_complexity": "High",
      "readiness_score": 49.0,
      "filing_status": "Needs product owner decision",
      "manual_sections": "Deductible options; Eligibility; Telematics discount",
      "form_or_rule_dependency": "Deductible options",
      "owner": "IT"
    },
    {
      "state": "OR",
      "product_line": "Farm and Ranch",
      "earned_premium": 25080712,
      "loss_ratio": 82.9,
      "combined_ratio": 111.4,
      "rate_indication": 12.0,
      "proposed_rate_change": 9.0,
      "filing_complexity": "High",
      "readiness_score": 52.0,
      "filing_status": "Needs product owner decision",
      "manual_sections": "Protection class; Territory factors; Renewal review",
      "form_or_rule_dependency": "Protection class",
      "owner": "Actuarial"
    },
    {
      "state": "WY",
      "product_line": "Auto",
      "earned_premium": 35779992,
      "loss_ratio": 82.8,
      "combined_ratio": 108.1,
      "rate_indication": 10.0,
      "proposed_rate_change": 7.5,
      "filing_complexity": "High",
      "readiness_score": 52.7,
      "filing_status": "Needs product owner decision",
      "manual_sections": "Territory factors; Deductible options; Renewal review",
      "form_or_rule_dependency": "Territory factors",
      "owner": "Compliance"
    },
    {
      "state": "CO",
      "product_line": "Home",
      "earned_premium": 52481568,
      "loss_ratio": 80.4,
      "combined_ratio": 109.9,
      "rate_indication": 11.1,
      "proposed_rate_change": 8.3,
      "filing_complexity": "High",
      "readiness_score": 55.9,
      "filing_status": "Needs product owner decision",
      "manual_sections": "Eligibility; Protection class; Territory factors",
      "form_or_rule_dependency": "Eligibility",
      "owner": "Actuarial"
    },
    {
      "state": "ID",
      "product_line": "Farm and Ranch",
      "earned_premium": 25365707,
      "loss_ratio": 79.7,
      "combined_ratio": 108.0,
      "rate_indication": 9.9,
      "proposed_rate_change": 7.5,
      "filing_complexity": "High",
      "readiness_score": 56.2,
      "filing_status": "Needs product owner decision",
      "manual_sections": "Protection class; Territory factors; Farm outbuilding coverage",
      "form_or_rule_dependency": "Protection class",
      "owner": "Product"
    },
    {
      "state": "WY",
      "product_line": "Home",
      "earned_premium": 46415294,
      "loss_ratio": 75.5,
      "combined_ratio": 105.2,
      "rate_indication": 8.2,
      "proposed_rate_change": 6.1,
      "filing_complexity": "High",
      "readiness_score": 59.4,
      "filing_status": "Needs compliance packet",
      "manual_sections": "Telematics discount; Territory factors; Protection class",
      "form_or_rule_dependency": "Telematics discount",
      "owner": "IT"
    }
  ],
  "automationQueue": [
    {
      "segment_id": "CA-FR-03",
      "state": "CA",
      "state_name": "California",
      "product_line": "Farm and Ranch",
      "territory": "Wildland interface",
      "geography_type": "wildfire",
      "rate_environment": "complex",
      "exposure_index": 71.2,
      "inspection_completion": 69.7,
      "telematics_eligible": 29.4,
      "automation_approval_rate": 36.1,
      "guideline_exception_rate": 37.0,
      "baseline_retention": 73.6,
      "owner": "Actuarial",
      "earned_premium": 7790702,
      "written_premium": 8193163,
      "incurred_losses": 8864640,
      "loss_ratio": 113.8,
      "combined_ratio": 142.5,
      "retention": 72.9,
      "claim_frequency": 10.3,
      "target_gap": 48.5,
      "rate_indication": 18,
      "review_score": 98.4,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "CA-AU-03",
      "state": "CA",
      "state_name": "California",
      "product_line": "Auto",
      "territory": "Wildland interface",
      "geography_type": "wildfire",
      "rate_environment": "complex",
      "exposure_index": 71.2,
      "inspection_completion": 63.6,
      "telematics_eligible": 49.5,
      "automation_approval_rate": 35.9,
      "guideline_exception_rate": 36.2,
      "baseline_retention": 70.0,
      "owner": "Underwriting",
      "earned_premium": 10425072,
      "written_premium": 10762363,
      "incurred_losses": 10812389,
      "loss_ratio": 103.7,
      "combined_ratio": 129.2,
      "retention": 70.1,
      "claim_frequency": 10.4,
      "target_gap": 35.2,
      "rate_indication": 18,
      "review_score": 85.2,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "CO-FR-03",
      "state": "CO",
      "state_name": "Colorado",
      "product_line": "Farm and Ranch",
      "territory": "Wildland interface",
      "geography_type": "wildfire",
      "rate_environment": "complex",
      "exposure_index": 61.3,
      "inspection_completion": 67.3,
      "telematics_eligible": 31.3,
      "automation_approval_rate": 46.3,
      "guideline_exception_rate": 36.2,
      "baseline_retention": 75.4,
      "owner": "Underwriting",
      "earned_premium": 7244669,
      "written_premium": 7436384,
      "incurred_losses": 7496522,
      "loss_ratio": 103.5,
      "combined_ratio": 132.5,
      "retention": 74.6,
      "claim_frequency": 10.6,
      "target_gap": 38.5,
      "rate_indication": 18,
      "review_score": 83.5,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "CA-FR-04",
      "state": "CA",
      "state_name": "California",
      "product_line": "Farm and Ranch",
      "territory": "Mountain and hail belt",
      "geography_type": "weather",
      "rate_environment": "complex",
      "exposure_index": 63.7,
      "inspection_completion": 68.4,
      "telematics_eligible": 37.1,
      "automation_approval_rate": 44.1,
      "guideline_exception_rate": 35.3,
      "baseline_retention": 76.8,
      "owner": "Claims",
      "earned_premium": 6765726,
      "written_premium": 7058660,
      "incurred_losses": 6993675,
      "loss_ratio": 103.4,
      "combined_ratio": 131.3,
      "retention": 76.7,
      "claim_frequency": 10.5,
      "target_gap": 37.3,
      "rate_indication": 18,
      "review_score": 82.2,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "CA-HO-03",
      "state": "CA",
      "state_name": "California",
      "product_line": "Home",
      "territory": "Wildland interface",
      "geography_type": "wildfire",
      "rate_environment": "complex",
      "exposure_index": 71.2,
      "inspection_completion": 70.5,
      "telematics_eligible": 33.6,
      "automation_approval_rate": 39.3,
      "guideline_exception_rate": 39.4,
      "baseline_retention": 71.9,
      "owner": "Product",
      "earned_premium": 13928513,
      "written_premium": 14317271,
      "incurred_losses": 13521559,
      "loss_ratio": 97.1,
      "combined_ratio": 126.3,
      "retention": 71.3,
      "claim_frequency": 10.1,
      "target_gap": 32.3,
      "rate_indication": 18,
      "review_score": 80.1,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "CO-AU-03",
      "state": "CO",
      "state_name": "Colorado",
      "product_line": "Auto",
      "territory": "Wildland interface",
      "geography_type": "wildfire",
      "rate_environment": "complex",
      "exposure_index": 61.3,
      "inspection_completion": 67.9,
      "telematics_eligible": 50.1,
      "automation_approval_rate": 47.0,
      "guideline_exception_rate": 37.4,
      "baseline_retention": 70.5,
      "owner": "Product",
      "earned_premium": 10327556,
      "written_premium": 10531555,
      "incurred_losses": 10150070,
      "loss_ratio": 98.3,
      "combined_ratio": 123.6,
      "retention": 70.1,
      "claim_frequency": 10.3,
      "target_gap": 29.6,
      "rate_indication": 18,
      "review_score": 73.4,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "CA-HO-04",
      "state": "CA",
      "state_name": "California",
      "product_line": "Home",
      "territory": "Mountain and hail belt",
      "geography_type": "weather",
      "rate_environment": "complex",
      "exposure_index": 63.7,
      "inspection_completion": 71.4,
      "telematics_eligible": 29.3,
      "automation_approval_rate": 41.8,
      "guideline_exception_rate": 36.2,
      "baseline_retention": 71.8,
      "owner": "Underwriting",
      "earned_premium": 13863420,
      "written_premium": 14277518,
      "incurred_losses": 13021507,
      "loss_ratio": 93.9,
      "combined_ratio": 123.8,
      "retention": 71.3,
      "claim_frequency": 9.9,
      "target_gap": 29.8,
      "rate_indication": 18,
      "review_score": 73.2,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "WY-FR-03",
      "state": "WY",
      "state_name": "Wyoming",
      "product_line": "Farm and Ranch",
      "territory": "Wildland interface",
      "geography_type": "wildfire",
      "rate_environment": "light",
      "exposure_index": 51.4,
      "inspection_completion": 67.2,
      "telematics_eligible": 35.7,
      "automation_approval_rate": 47.7,
      "guideline_exception_rate": 30.6,
      "baseline_retention": 76.7,
      "owner": "Claims",
      "earned_premium": 6616953,
      "written_premium": 6783193,
      "incurred_losses": 6482481,
      "loss_ratio": 98.0,
      "combined_ratio": 126.7,
      "retention": 77.5,
      "claim_frequency": 10.2,
      "target_gap": 32.7,
      "rate_indication": 18,
      "review_score": 71.6,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "CA-AU-04",
      "state": "CA",
      "state_name": "California",
      "product_line": "Auto",
      "territory": "Mountain and hail belt",
      "geography_type": "weather",
      "rate_environment": "complex",
      "exposure_index": 63.7,
      "inspection_completion": 74.5,
      "telematics_eligible": 47.5,
      "automation_approval_rate": 43.8,
      "guideline_exception_rate": 34.9,
      "baseline_retention": 71.2,
      "owner": "Actuarial",
      "earned_premium": 11126847,
      "written_premium": 11523766,
      "incurred_losses": 10813432,
      "loss_ratio": 97.2,
      "combined_ratio": 123.8,
      "retention": 70.1,
      "claim_frequency": 9.8,
      "target_gap": 29.8,
      "rate_indication": 18,
      "review_score": 71.2,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "CO-FR-04",
      "state": "CO",
      "state_name": "Colorado",
      "product_line": "Farm and Ranch",
      "territory": "Mountain and hail belt",
      "geography_type": "weather",
      "rate_environment": "complex",
      "exposure_index": 54.2,
      "inspection_completion": 69.0,
      "telematics_eligible": 37.2,
      "automation_approval_rate": 48.3,
      "guideline_exception_rate": 28.2,
      "baseline_retention": 77.4,
      "owner": "Actuarial",
      "earned_premium": 7562563,
      "written_premium": 7845273,
      "incurred_losses": 7376158,
      "loss_ratio": 97.5,
      "combined_ratio": 126.8,
      "retention": 76.5,
      "claim_frequency": 9.7,
      "target_gap": 32.8,
      "rate_indication": 18,
      "review_score": 70.7,
      "action_score": 100,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "WA-FR-03",
      "state": "WA",
      "state_name": "Washington",
      "product_line": "Farm and Ranch",
      "territory": "Wildland interface",
      "geography_type": "wildfire",
      "rate_environment": "moderate",
      "exposure_index": 48.9,
      "inspection_completion": 69.5,
      "telematics_eligible": 37.5,
      "automation_approval_rate": 51.5,
      "guideline_exception_rate": 28.3,
      "baseline_retention": 77.7,
      "owner": "IT",
      "earned_premium": 7023337,
      "written_premium": 7150103,
      "incurred_losses": 6690017,
      "loss_ratio": 95.3,
      "combined_ratio": 123.5,
      "retention": 78.2,
      "claim_frequency": 10.4,
      "target_gap": 29.5,
      "rate_indication": 18,
      "review_score": 65.0,
      "action_score": 97.9,
      "recommendation": "Tighten guideline and inspection trigger"
    },
    {
      "segment_id": "CA-FR-02",
      "state": "CA",
      "state_name": "California",
      "product_line": "Farm and Ranch",
      "territory": "Rural farm belt",
      "geography_type": "rural",
      "rate_environment": "complex",
      "exposure_index": 48.6,
      "inspection_completion": 72.5,
      "telematics_eligible": 30.2,
      "automation_approval_rate": 46.7,
      "guideline_exception_rate": 27.7,
      "baseline_retention": 80.4,
      "owner": "Underwriting",
      "earned_premium": 7496249,
      "written_premium": 7633631,
      "incurred_losses": 7150945,
      "loss_ratio": 95.4,
      "combined_ratio": 124.2,
      "retention": 79.5,
      "claim_frequency": 9.7,
      "target_gap": 30.2,
      "rate_indication": 18,
      "review_score": 64.8,
      "action_score": 97.3,
      "recommendation": "Route to underwriting review"
    }
  ],
  "requirements": [
    {
      "requirement_id": "BR-001",
      "capability": "Loss ratio monitor",
      "business_requirement": "Create state and product alert when monthly loss ratio is 8 pts above rolling target.",
      "requesting_team": "Product",
      "delivery_partner": "IT",
      "priority": "High",
      "status": "Ready for sizing"
    },
    {
      "requirement_id": "BR-002",
      "capability": "Inspection trigger",
      "business_requirement": "Route property risks to review when exposure index is high and inspection completion is below target.",
      "requesting_team": "Underwriting",
      "delivery_partner": "IT",
      "priority": "High",
      "status": "In review"
    },
    {
      "requirement_id": "BR-003",
      "capability": "Filing packet tracker",
      "business_requirement": "Expose manual sections, rate indication, proposed change, and compliance packet status in one view.",
      "requesting_team": "Compliance",
      "delivery_partner": "Product",
      "priority": "High",
      "status": "Accepted"
    },
    {
      "requirement_id": "BR-004",
      "capability": "Telematics adoption",
      "business_requirement": "Identify auto segments where telematics eligibility is high but enrollment lags.",
      "requesting_team": "Product",
      "delivery_partner": "Underwriting",
      "priority": "Medium",
      "status": "Drafted"
    },
    {
      "requirement_id": "BR-005",
      "capability": "Farm outbuilding review",
      "business_requirement": "Flag farm segments with severity movement and missing outbuilding documentation.",
      "requesting_team": "Claims",
      "delivery_partner": "Underwriting",
      "priority": "Medium",
      "status": "Ready for sizing"
    },
    {
      "requirement_id": "BR-006",
      "capability": "Retention watchlist",
      "business_requirement": "Rank profitable segments with retention pressure before rate changes are submitted.",
      "requesting_team": "Product",
      "delivery_partner": "Actuarial",
      "priority": "Medium",
      "status": "In review"
    },
    {
      "requirement_id": "BR-007",
      "capability": "Guideline exception QA",
      "business_requirement": "Sample automated approvals where guideline exception rate exceeds threshold.",
      "requesting_team": "Underwriting",
      "delivery_partner": "Compliance",
      "priority": "High",
      "status": "Accepted"
    },
    {
      "requirement_id": "BR-008",
      "capability": "Implementation handoff",
      "business_requirement": "Track product decision, actuarial support, IT requirement, and effective date readiness.",
      "requesting_team": "Product",
      "delivery_partner": "IT",
      "priority": "Medium",
      "status": "Drafted"
    }
  ],
  "productMix": [
    {
      "productLine": "Home",
      "earnedPremium": 290750436,
      "combinedRatio": 106.1
    },
    {
      "productLine": "Auto",
      "earnedPremium": 226441503,
      "combinedRatio": 107.8
    },
    {
      "productLine": "Farm and Ranch",
      "earnedPremium": 163545389,
      "combinedRatio": 116.6
    },
    {
      "productLine": "Umbrella",
      "earnedPremium": 57394443,
      "combinedRatio": 80.2
    }
  ]
};
